### ISSUE TITLE
Consistent morph ball bomb crashes in lava

### ISSUE THREAD

**Issue by CronusofASoul** [BashPrime/metroid-prime-randomizer#23]
Version: 1.3.1
Permalink: Njc4NzI5NjQ2NDQ3MDAxNiwxLjMuMSxIRzY5TkhBQUFBQUFKM0I=

Description of problem: Consistent morph ball bomb crashes in lava
Running using Nintendont on a Wii U in vWii mode

Spoiler log (if available):
[Prime Randomizer - EM1Q53TS Spoiler.txt] (https://github.com/etaylor8086/metroid-prime-randomizer/files/4366629/Prime.Randomizer.-.EM1Q53TS.Spoiler.txt)

Verify ISO file (if available): SHA1: 1A737910B55B59C6AD91BE9E3E3C43517FD52EFB
(Verified by 7-Zip and Dolphin; matches GameTDB for v1.02)

**Comment by etaylor8086** [comment]
This is a known issue that I think has to do with v1.02 patched games. I'm actually releasing v2.0.0 of the randomizer which contains several significant patcher updates, though I don't know if the lava bomb crashing has been fixed.

I suggest using a v1.00 base ISO.

**Comment by etaylor8086** [comment]
@CronusofASoul what version of Nintendont are you using? Can you take a picture of your Nintendont settings?

**Comment by CronusofASoul** [comment]
![Nintendont Settings Screenshot 2020-03-23 09-16-52](https://user-images.githubusercontent.com/4459549/77320572-31fb0100-6ce7-11ea-8056-94a5dfc0522b.png)
![Nintendont Settings Screenshot 2020-03-23 09-16-58](https://user-images.githubusercontent.com/4459549/77320576-33c4c480-6ce7-11ea-9460-b519e6dbec96.png)
![Nintendont Settings Screenshot 2020-03-23 09-17-09](https://user-images.githubusercontent.com/4459549/77320579-34f5f180-6ce7-11ea-88e2-bd7cf1c3d19a.png)
![Nintendont Settings Screenshot 2020-03-23 09-17-18](https://user-images.githubusercontent.com/4459549/77320582-358e8800-6ce7-11ea-98a6-50593e726a0d.png)

**Comment by BashPrime** [comment]
Hello, sorry to take so long following up but I have been able to reproduce this with your permalink, nintendont settings and my 1.02 iso. I'm not sure what causes this yet but I'm investigating.

**Comment by BashPrime** [comment]
I'm 90% sure I figured out what's going on.

If you are patching with a 1.02 Metroid Prime ISO with progressive damage, the crash can be reproduced by bombing while submerged in lava or water.

**Comment by BashPrime** [comment]
Tested and confirmed a fix from Syncathetic. Will pull the update from randomprime as soon as it hits master. Marking as closed.
