### ISSUE TITLE
Incorrect location reference

### ISSUE THREAD

**Issue by SauceRelic** [BashPrime/metroid-prime-randomizer#35]
https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/chozoRuins.ts#L485

The exit from Hall of the Elders to Furnace incorrectly references Energy Core instead. This allows impossible seeds to be generated with specific settings, e.g. starting area Reflecting Pool (either), starting items ice beam, morph ball and missile launcher, and point of no return items allowed. Logically, the only accessible location at this point is Incinerator Drone, which would have bombs to allow escape from the room, but the check is inaccessible since bombs are required to traverse the furnace tunnel. Example seed: OUJGNVY4U1VSUSAxSkY5Qk5DVy0zTEpYSEs3R1pDWkswRU5NV0FIQ0kzS0I0TE1HWlpRNUowNVNQMENWSDZMTU8tMC0w

**Comment by BashPrime** [comment]
Good catch, thanks. Fixed in 1750dda.
