### ISSUE TITLE
Missing exit

### ISSUE THREAD

**Issue by SauceRelic** [BashPrime/metroid-prime-randomizer#36]
https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/chozoRuins.ts#L388

Exit from Energy Core to Gathering Hall is missing, limiting logic routing options. This exit should require no items.

**Comment by BashPrime** [comment]
Good catch, thanks. Fixed in 1750dda
