### ISSUE TITLE
Logic Errors

### ISSUE THREAD

**Issue by SauceRelic** [BashPrime/metroid-prime-randomizer#37]
Finished trawling through the logic for a tracker update, here's everything I found:

**Potential logic errors/changes**
- waterfall cavern backwards might require morph: https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/tallonOverworld.ts#L59
- furnace to hote doesn't need space jump (jump from some rubble or double bomb jump, probably add as a trick option): https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/chozoRuins.ts#L438
- monitor station has no exit to triclops pit: https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/magmoorCaverns.ts#L41
- ice ruins east exit to phendrana shorelines requires no items; go through plaza walkway: https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phendranaDrifts.ts#L81
- frozen pike has no exit to research core, requirements should be wave and ice beams: https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phendranaDrifts.ts#L261
- hunter cave exit to phendrana's edge requires morph to traverse lower edge tunnel: https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phendranaDrifts.ts#L342

**Minor stuff (mostly simplifying boolean statements, won't actually affect logic)**
- phendrana shorelines exit to ice ruins east; "hasMissiles" also fulfills "canBreakIce", making the latter redundant: https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phendranaDrifts.ts#L27
- chapel of the elders item being in logic is not affected by oob settings or requirements; "infiniteSpeedReqs" cannot be true without "hasMissiles" being true, which alone puts item in logic: https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phendranaDrifts.ts#L54
- ore processing "spiderReqs"/"spiderGrappleReqs" for storage depot b item and main quarry exit redundantly require bombs: https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phazonMines.ts#L83 https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phazonMines.ts#L89

**Comment by BashPrime** [comment]
I've been overdue on passing through the logic. Thank you for the detailed analysis!

**Comment by BashPrime** [comment]
Thanks again for taking the time to audit the logic. I've applied the major and virtually all the minor fixes.
