### ISSUE TITLE
Potential for Point of No Return softlock

### ISSUE THREAD

**Issue by SauceRelic** [BashPrime/metroid-prime-randomizer#38]
Quarantine Cave exit to Ruined Courtyard does not properly account for labs pathing: in addition to current requirements, labs require scan visor and missiles, as well as boost ball and bombs if Observatory trick is not enabled. Frozen Pike climb also ignores the option to boost through bomb tunnels, causing an opposite and less critical issue of being too restrictive. Return through Quarantine Access seems OK.

https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phendranaDrifts.ts#L163

**Comment by BashPrime** [comment]
Good catch, thanks. Fixed, will push in 2.5.0
