### ISSUE TITLE
Ruined Courtyard misreference

### ISSUE THREAD

**Issue by SauceRelic** [BashPrime/metroid-prime-randomizer#39]
Spider ball option for climbing Ruined Courtyard checks for the spider ball item instead of canSpider, so if point of no return items are allowed an item could be in logic past this exit without actually being able to climb the courtyard or pass North Quarantine Tunnel.

https://github.com/BashPrime/metroid-prime-randomizer/blob/826460f9cc4af04aa3d92e74c266272723ce19e4/src/electron/models/prime/regions/phendranaDrifts.ts#L126

**Comment by BashPrime** [comment]
Thanks, fixed for 2.5.0 release.
