### ISSUE TITLE
Triclops Pit logic

### ISSUE THREAD

**Issue by SauceRelic** [BashPrime/metroid-prime-randomizer#43]
https://github.com/BashPrime/metroid-prime-randomizer/blob/b84848883f2a34fedd6b2d46c482dc9d4d5416de/src/electron/models/prime/regions/magmoorCaverns.ts#L38

Trick for using charge beam omits actually requiring charge beam

**Comment by BashPrime** [comment]
Fixed, will be included in 2.6.0 release
