### ISSUE TITLE
Main Plaza logic

### ISSUE THREAD

**Issue by SauceRelic** [BashPrime/metroid-prime-randomizer#44]
https://github.com/BashPrime/metroid-prime-randomizer/blob/11e2ba78245a6521d8c28e3f07b8673518bcbe32/src/electron/models/prime/regions/chozoRuins.ts#L27-L34

2.5.0 changes for Main Plaza _Grapple_ Ledge were accidentally applied to Main Plaza _Locked Door_ Ledge instead

**Comment by BashPrime** [comment]
I am an *idiot*.

Thanks, Sauce.

**Comment by BashPrime** [comment]
Fixed, will be included in 2.6.0 release
