### ISSUE TITLE
im confuzz

### ISSUE THREAD

**Issue by Mephistoop** [BashPrime/metroid-prime-randomizer#51]
I can't figure out how to open the script. Also, the discord link doesn't work for me. Is there a tutorial I'm missing??

**Comment by DreiPixel** [comment]
just install the program?
https://github.com/BashPrime/metroid-prime-randomizer/releases/tag/v2.5.0

**Comment by BashPrime** [comment]
Hi @Mephistoop,

If you're just trying to run the randomizer program, you can download it at the link @DreiPixel provided (or this link: https://github.com/BashPrime/metroid-prime-randomizer/releases/latest) for your given operating system.

If you're trying to build from source, check out the installation instructions: https://github.com/BashPrime/metroid-prime-randomizer/releases/latest
