### ISSUE TITLE
Lava Lake suitless doesn't require E-Tanks

### ISSUE THREAD

**Issue by Minwerdi** [BashPrime/metroid-prime-randomizer#53]
https://github.com/BashPrime/metroid-prime-randomizer/blob/b84848883f2a34fedd6b2d46c482dc9d4d5416de/src/electron/models/prime/regions/magmoorCaverns.ts#L13-L17

https://github.com/BashPrime/metroid-prime-randomizer/blob/b84848883f2a34fedd6b2d46c482dc9d4d5416de/src/common/data/settingsDetails.ts#L422-L425

The logic for the Lava Lake item suitless (top block) only checks for missiles and Space Jump. It does not check for 4 Energy Tanks, despite the trick description (bottom block) saying it expects 4 E-Tanks and SJ.

**Comment by BashPrime** [comment]
Thanks for reporting. Sorry for the oversight, I will fix this for the next release.

**Comment by BashPrime** [comment]
Fixed, will be available in the next release.
