### ISSUE TITLE
Requesting information about automatic Frigate Skip.

### ISSUE THREAD

**Issue by Plessy** [BashPrime/metroid-prime-randomizer#66]
I've been doing some casual runs using the randomizer, and I like to do frigate and do all the scans. Why was this changed to be always on, skipping a boss? I really liked having the option. I understand that you would want to have that for the sake of speedrunners, but wouldn't it make more sense just to start it as on? Or is there a bug now preventing Frigate from working properly that caused this? I'm pretty baffled by this decision, as it impacts my experience with the game with no outward reason for it. I'm not exactly saying that you should change it back to an option, but I'm just putting it out there that there are parts of the community that this has negatively affected. I'll probably just stick to the old version unless this is reverted. Great work in general though! It has been a blast to be able to make a game I love feel so fresh!

**Comment by BashPrime** [comment]
There is a bug I discovered with the version of the Prime patcher that this app uses, where starting on Frigate with nonstandard starting items will cause you to lose them upon leaving Frigate, effectively making seeds with custom starting items unbeatable.

As a head's up, Prime 1 randomizer is effectively moving to Randovania and being supported there, so I am no longer actively developing this app; otherwise, this would be something I would address in a future software update.

**Comment by BashPrime** [comment]
Forgot to follow up, but most Prime 1 randovania discussion is happening on the Prime randomizer Discord server if you're not already in there: http://discord.gg/WWGcay6

**Comment by Plessy** [comment]
Thanks for the details! I actually knew about the Tallon IV item loss, but I didn't put 2+2 together.  Thanks for all your hard work! By the way, what is Randovania? Quickly googling it says it's a randomizer for 2? Does that mean that 1's support is getting wrapped into that?

**Comment by BashPrime** [comment]
Randovania is another Randomizer app made by my friend Darkszero: https://github.com/randovania/randovania

Until recently it only supported Metroid Prime 2, but current developer builds have solo and multiworld support for Metroid Prime. I believe it's at nearly complete feature parity (and in several cases it has even more features) except for point of no return checks, and I argue that it has a better item filling logic.

Dev builds can be found here: https://github.com/randovania/randovania/actions/workflows/tests.yml

**Comment by Plessy** [comment]
Multiworld you say? That sounds wild. I'll be sure to check it out!
